Fixes nil aws_params:
```
NoMethodError: undefined method `[]' for nil:NilClass> with backtrace:
         # ./lib/cloud/aws/aws_provider.rb:32:in `rescue in aws_accessible?'
         # ./lib/cloud/aws/aws_provider.rb:28:in `aws_accessible?'
         # ./lib/cloud/aws/cloud.rb:34:in `initialize'
         # ./spec/integration/lifecycle_spec.rb:59:in `new'
         # ./spec/integration/lifecycle_spec.rb:59:in `block (4 levels) in <top (required)>'
         # ./spec/integration/lifecycle_spec.rb:58:in `block (3 levels) in <top (required)>'
     # ./spec/integration/lifecycle_spec.rb:58:in `block (3 levels) in <top (required)>'
```

[finishes #152249108](https://www.pivotaltracker.com/story/show/152249108)

Signed-off-by: Luan Santos <lsantos@pivotal.io>