Use an instance type with raw storage
Upgrading to t2 types because of the m3 deprecation means our default
instance type does not have raw storage. For some tests we require this
so we will now use i3.large for those tests.

fixes
```
Error: CPI error 'Bosh::Clouds::CloudError' with message 'raw_instance_storage requested for instance type 't2.medium' that does not have instance storage' in 'create_vm' CPI method
```

Signed-off-by: Brian Cunnie <bcunnie@pivotal.io>