Lifecycle spec runs to completion
- endpoints are no longer hard-coded us-east-1
- code mistakenly re-introduced has been removed
- errant `require 'pry-byebug'` removed

fixes:
```
AWS was not able to validate the provided access credentials
```
```
Failure/Error: 'default_key_name' => default_key_name,
     NameError:
       undefined local variable or method `default_key_name' for #<RSpec::ExampleGroups::BoshAwsCloudCloud_2::ManualNetworking::LoggingRequestId::WhenRequestIdIsNOTPresentInTheContext:0x007fe9e6be7aa8>
       Did you mean?  @default_key_name
```
```
Failure/Error: let(:security_groups) { get_security_group_ids(@subnet_id) }
     ArgumentError:
       wrong number of arguments (given 1, expected 0)
```

Signed-off-by: Brian Cunnie <bcunnie@pivotal.io>

[#135803903](https://www.pivotaltracker.com/story/show/135803903)