Terraformed aws_iam_instance_profile is correctly propagated
- jq does not like `-` in key name
fixes:
```
error: e2e is not defined
.ELB-e2e     1 compile error
```

- terraform needs to create aws_iam_instance_profile
Fixes
```
L Error: Unknown CPI error 'Unknown' with message 'Value (season-jaguar00943a6e008d0f1a3753e87b0f) for parameter iamInstanceProfile.name is invalid. Invalid IAM Instance Profile name' in 'create_vm' CPI method
```

[#133222913](https://www.pivotaltracker.com/story/show/133222913)

Signed-off-by: Brian Cunnie <bcunnie@pivotal.io>