Allow instance metadata_options to be set in cpi config
- This allows users to disable IMDSv1 and force IMDSv2
- Doing so requires a stemcell that supports IMDSv2. Earlier stemcells will time out on creation with
  ```
  Error: Timed out pinging VM
  ```

Co-Authored-By: Rajan Agaskar <ragaskar@vmware.com>
Co-Authored-By: Julian Hjortshoj <hjortshojj@vmware.com>

[#180052419](https://www.pivotaltracker.com/story/show/180052419)